/*
  Warnings:

  - Changed the type of `taskType` on the `tasks` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- CreateEnum
CREATE TYPE "TaskType" AS ENUM ('ASSESS_SITUATION', 'COMPOSE_PROJECT_TEAM', 'SET_BUSINESS_OBJECTIVES', 'DERIVE_DATA_SCIENCE_TARGETS', 'CREATE_PROJECT_PLAN', 'IDENTIFY_DATA_SOURCES', 'ACQUIRE_DATA', 'DESCRIBE_DATA', 'EXPLORE_DATA', 'ASSESS_DATA_QUALITY', 'PREPARE_DATA', 'DEVELOP_DATA_PIPELINE', 'DEFINE_HYPOTHESIS', 'SELECT_ANALYTICAL_MODEL', 'DESIGN_TEST_FOR_ANALYTICAL_MODEL', 'DEVELOP_ANALYTICAL_MODEL', 'ASSESS_ANALYTICAL_MODEL', 'DEVELOP_ANALYTICAL_PIPELINE', 'ASSESS_ANALYTICAL_RESULTS', 'EVALUATE_PROCESS', 'PERFORM_CHECKPOINT_DECISION', 'PERFORM_IMPACT_ASSESSMENT', 'PLAN_DEPLOYMENT', 'PLAN_MONITORING_AND_MAINTENANCE', 'TEST_DEPLOYMENT', 'PERFORM_BUSINESS_INTEGRATION', 'FINALIZE_PROJECT', 'MONITOR_MODEL_PERFORMANCE', 'MAINTAIN_DATA_PIPELINE', 'UPDATE_MODEL', 'CUSTOM');

-- AlterTable
ALTER TABLE "tasks" DROP COLUMN "taskType",
ADD COLUMN     "taskType" "TaskType" NOT NULL;

-- DropEnum
DROP TYPE "public"."StandardTaskType";

-- CreateIndex
CREATE INDEX "tasks_projectPlanId_taskType_idx" ON "tasks"("projectPlanId", "taskType");
