runtime: nodejs20
entrypoint: npm start

env: standard

instance_class: F1

handlers:
  #API-Endpunkte (alles unter /api) werden vom Backend behandelt
  - url: /api/.*
    script: auto

  # Statische Dateien (Frontend-Build)
  - url: /
    static_files: ../frontend/dist/index.html
    upload: ../frontend/dist/index.html

  - url: /(.*)
    static_files: ../frontend/dist/\1
    upload: ../frontend/dist/(.*)

env_variables:
  NODE_ENV: production
