runtime: nodejs20
entrypoint: npm start

env: standard

instance_class: F1

handlers:
  # API-Endpunkte (alles unter /api) werden vom Backend behandelt
  - url: /api/.*
    script: auto

  # Statische Dateien (Frontend-Build)
  - url: /
    static_files: dist/frontend/index.html
    upload: dist/frontend/index.html

  - url: /(.*)
    static_files: dist/frontend/\1
    upload: dist/frontend/(.*)

env_variables:
  NODE_ENV: production
